TOKEN = "6420807698:AAF5KaKictwLAPBz3Np3hB6CLqcAZ1V9B50"
CHAT_ID = "-1002102303733"
BASE_URL_API = "https://api-celestia-1.latamnodes.org"
BASE_URL_RPC = "https://rpc-celestia-1.latamnodes.org"
# BASE_URL_API = "https://api-celestia.mzonder.com"
# BASE_URL_RPC = "https://rpc-celestia.mzonder.com"
DEBUG = False
PORCENTAJE = False
MIN_FREE_SPACE = 11 # Definir el porcentaje o valor fijo minimo de espacio libre requerido en GB
VALOPER_ADDRESS = "celestiavaloper14v4ush42xewyeuuldf6jtdz0a7pxg5fwrlumwf"  # La dirección de tu validador